[package]
name = "tensor"
version = "0.1.0"
edition = "2024"

[dependencies]
num-traits = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6.0"
objc2-metal = "0.3.1"
objc2-metal-performance-shaders = "0.3.1"
